name: Common Docker Build Workflow

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      base-tag:
        type: string
        required: false
      context:
        type: string
        default: ./
        required: false
      dockerfile:
        type: string
        default: ./Dockerfile
        required: false
      target:
        type: string
        required: false
      arguments:
        type: string
        required: false
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build and push
        uses: niqzart/ffs-devops/docker-build@main
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}
          tag: ${{ inputs.tag }}
          base-tag: ${{ inputs.base-tag }}
          context: ${{ inputs.context }}
          dockerfile: ${{ inputs.dockerfile }}
          target: ${{ inputs.target }}
          arguments: ${{ inputs.arguments }}
