name: Common Docker Build & Deploy Workflow

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      images:
        type: string
        required: true
      context:
        type: string
        required: false
      dockerfile:
        type: string
        required: false
      target:
        type: string
        required: false
      arguments:
        type: string
        required: false
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true
      SERVER_IP:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      tag: ${{ inputs.tag }}
      context: ${{ inputs.context }}
      dockerfile: ${{ inputs.dockerfile }}
      target: ${{ inputs.target }}
      arguments: ${{ inputs.arguments }}
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/docker-deploy.yml
    with:
      images: ${{ inputs.images }}
    secrets: inherit
