name: Common Docker Build Workflow

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      context:
        type: string
        required: false
      dockerfile:
        type: string
        required: false
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build and push
        uses: niqzart/ffs-devops/docker-build@main
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_HUB_USERNAME }}
          tag: ${{ inputs.tag }}
          context: ${{ inputs.context }}
          dockerfile: ${{ inputs.dockerfile }}
